### ISSUE TITLE
Add to Awesome Textpattern?

### ISSUE THREAD

**Issue by drmonkeyninja** [NicolasGraph/wp-to-txp#1]
This looks really useful. Would you like it adding to the [Awesome Textpattern](https://github.com/drmonkeyninja/awesome-textpattern) list? Perhaps under "Resources".

**Comment by NicolasGraph** [comment]
[Here it is](https://github.com/drmonkeyninja/awesome-textpattern/pull/38) @drmonkeyninja ; thanks for the suggestion.
